version: '2.1'

services:
  mailserver:
    image: hardware/mailserver:1.1-stable
    container_name: mailserver
    domainname: ${mail_server_host}.${postfix_admin_domain}                  # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: mail
    restart: always
    ports:
      - "25:25"       # SMTP                - Required
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    environment:
      - DBPASS=${docker_compose_password}          # MariaDB database password (required)
      - RSPAMD_PASSWORD=${docker_compose_password}  # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld...   # Add additional domains separated by commas (needed for dkim keys etc.)
    # - ENABLE_POP3=true                    # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true               # Enable fetchmail forwarding
    # - DISABLE_CLAMAV=true                 # Disable virus scanning
    # - DISABLE_SIGNING=true                # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true            # Disable greylisting policy
    # - DISABLE_RATELIMITING=true           # Disable ratelimiting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - /mnt/docker/mail:/var/mail
      - /mnt/docker/nginx/certs:/etc/letsencrypt
    depends_on:
      - mariadb
      - redis

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: ${mail_server_host}.${postfix_admin_domain}
    hostname: mail
    restart: always
    environment:
      - DBPASS=${docker_compose_password}
    depends_on:
      - mailserver
      - mariadb

  # Web server
  # https://github.com/Wonderfall/dockerfiles/tree/master/boring-nginx
  # https://nginx.org/
  # Configuration : https://github.com/hardware/mailserver/wiki/Reverse-proxy-configuration
  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    restart: always
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /mnt/docker/nginx/sites-enabled:/sites-enabled
      - /mnt/docker/nginx/conf:/conf.d
      - /mnt/docker/nginx/log:/var/log/nginx
      - /mnt/docker/nginx/certs:/certs
    depends_on:
      - mailserver
      - postfixadmin

  # Database
  # https://github.com/docker-library/mariadb
  # https://mariadb.org/
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    restart: always
    # Info : These variables are ignored when the volume already exists (databases created before).
    environment:
      - MYSQL_ROOT_PASSWORD=${docker_compose_password}
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=${docker_compose_password}
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql

  # Cache Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:3.2-alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - /mnt/docker/redis/db:/data

